apiVersion: apps/v1
kind: Deployment
metadata:
  name: banvic-postgres
  namespace: banvic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: banvic-postgres
  template:
    metadata:
      labels:
        app: banvic-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.15-alpine3.24@sha256:075f7ba66bc9b3ce7d6b8b635208ff61cd7cf1a67d71ec530eec5d7ae0cbe571
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: banvic-postgres-secret
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "" -d ""
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 6
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U "" -d ""
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: banvic-postgres-pvc
